routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//texting purpose
Route::post('/', 'testcontroller@save')->name('test.post');
Route::get('/', 'testcontroller@index');

//end testing purpose

//manageinvoice

Route::post('/invoice', 'invoice\ManageInvoice@store')->name('inv.store.post');
Route::get('/invoice/create', 'invoice\ManageInvoice@create')->name('invoice.create.get');
Route::get('/invoice/{id}/download/pdf', 'invoice\ManageInvoice@generatePdfInvoice')->name('invoice.pdf.download');
Route::get('/invoice/{id}/details', 'invoice\ManageInvoice@InvoiceDetails')->name('invoice.details');
Route::get('/invoice', 'invoice\ManageInvoice@index')->name('invoice.dashboard.get');


//product Manage
Route::resource('product', 'product\ManageProduct');
Route::get('product/view/{id}', 'product\ManageProduct@viewdetails');
//end product Manage
//
///
///  //product client
Route::resource('customer', 'customer\CustomerController');

//end product client

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    //
}

app/Http/Controllers/customer/CustomerController.php
<?php

namespace App\Http\Controllers\customer;

use App\Customer;
use App\Http\Controllers\Controller;
use App\Http\Requests\customer as customerrequest;
use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       return view('client.pages.customer.showall');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('client.pages.customer.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(customerrequest $request)
    {
        $s = new Customer();
        $s->name = $request->name;
        $s->mobile = $request->mobile;
        $s->email = $request->email;
        $s->person_name = $request->person_name;
        $s->street = $request->street;
        $s->locality = $request->locality;
        $s->city = $request->city;
        $s->state = $request->state;
        $s->country = $request->country;
        $s->pin = $request->pin;
        $s->gstin = $request->gstin;
        $s->save();
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function customerapi() {
        $g = Customer::all();
        $c = $g->count();
        return Datatables::of(Customer::query())->make(true);
    }

    public function apisearch(Request $request) {
        $query = $request->get('term','');

        $products = Customer::where('name', 'LIKE', '%' . $query . '%')->take(5)->get();

        $data=array();
        foreach ($products as $product) {
            $data[]=array('value'=>$product->name,
                'id'=>$product->id,
                'gstin'=>$product->gstin,
                'street'=>$product->street,
                'locality'=>$product->locality,
                'city'=>$product->city,
                'state'=>$product->state,
                'country'=>$product->country,
                'pin' => $product->pin,
                'person_name' => $product->person_name

            );
        }
        if(count($data))
            return $data;
        else
            return ['value'=>'No Result Found','id'=>''];
    }

}

resources/views/client/pages/customer/create.blade.php
@extends('client.structure')
@section('client.title', 'Create New Customer')
@section('client.menu.customer', 'm-menu__item--active')
@section('client')
    <div class="m-grid__item m-grid__item--fluid m-wrapper">
        <!-- BEGIN: Subheader -->
        <div class="m-subheader ">
            <div class="d-flex align-items-center">
                <div class="mr-auto">
                    <h3 class="m-subheader__title m-subheader__title--separator">
                        Dashboard
                    </h3>
                    <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                        <li class="m-nav__item m-nav__item--home">
                            <a href="#" class="m-nav__link m-nav__link--icon">
                                <i class="m-nav__link-icon la la-home"></i>
                            </a>
                        </li>
                        <li class="m-nav__separator">
                            -
                        </li>
                        <li class="m-nav__item">
                            <a href="" class="m-nav__link">
											<span class="m-nav__link-text">
												Customer
											</span>
                            </a>
                        </li>
                        <li class="m-nav__separator">
                            -
                        </li>
                        <li class="m-nav__item">
                            <a href="" class="m-nav__link">
											<span class="m-nav__link-text">
												Create New Customer
											</span>
                            </a>
                        </li>
                    </ul>
                </div>
                <div>
                </div>
            </div>
        </div>
        <!-- END: Subheader -->
        <div class="m-content">
            <!--begin::Portlet-->
            <div class="m-portlet">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <h3 class="m-portlet__head-text">
                                Create New Customer
                            </h3>
                        </div>
                    </div>


                </div>

                <!--begin::Form to add product-->
                <form class="m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed"  method="POST"
                      action="{{route('customer.store')}}">
                    {{ csrf_field() }}

                    <div class="m-portlet__body">

                        @if ($errors->any())

                        <div class="form-group m-form__group row">
                            <div class="col-lg-12">



                                    <div class="form-group m-form__group row">

                                        <div class="col-lg-12 col-md-12 col-sm-12">

                                            <div class="m-alert m-alert--icon m-alert--icon-solid m-alert--outline alert alert-danger alert-dismissible fade show" role="alert">
                                                <div class="m-alert__icon">
                                                    <i class="flaticon-exclamation-1"></i>
                                                    <span></span>
                                                </div>
                                                <div class="m-alert__text">
                                                    <strong>
                                                        OOPS! <br>
                                                    </strong>
                                                    @foreach ($errors->all() as $error)
                                                        {{ $error }} <br>

                                                    @endforeach
                                                </div>
                                                <div class="m-alert__close">
                                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>


                            </div>
                        </div>

                        @endif

                        <div class="form-group m-form__group row">
                            <div class="col-lg-3">
                                <label>
                                    Customer Name:
                                </label>
                                <div class="input-group m-input-group m-input-group--square">
														<span class="input-group-addon">
															<i class="la la-institution"></i>
														</span>
                                <input type="text" name="name" class="form-control m-input--air" placeholder="Name">

                                </div>
                            </div>
                            <div class="col-lg-3">
                                <label class="">
                                    Customer Email:
                                </label>
                                <div class="input-group m-input-group m-input-group--square">
														<span class="input-group-addon">
															<i class="la la-envelope"></i>
														</span>

                                <input type="email" name="email" class="form-control m-input--air" placeholder="Email">

                                </div>
                            </div>
                            <div class="col-lg-3">
                                <label>
Mobile Number:
                                </label>
                                <div class="input-group m-input-group m-input-group--square">
														<span class="input-group-addon">
															<i class="la la-mobile"></i>
														</span>
                                    <input name="mobile" type="number" class="form-control m-input--air" placeholder="">
                                </div>
                            </div>


                            <div class="col-lg-3">
                                <label>
GSTIN:
                                </label>
                                <div class="input-group m-input-group m-input-group--square">
														<span class="input-group-addon">
															<i class="la la-info"></i>
														</span>
                                    <input name="gstin" type="text" class="form-control m-input--air" placeholder="GSTIN">
                                </div>
                            </div>
                        </div>
                        <div class="form-group m-form__group row">
                                <div class="col-lg-4">
                                    <label>
                                        Contact Person Name:
                                    </label>
                                    <div class="input-group m-input-group m-input-group--square">
														<span class="input-group-addon">
															<i class="la la-user"></i>
														</span>
                                        <input type="text" name="person_name" class="form-control m-input--air" placeholder="Contact Person">

                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <label class="">
                                        Street:
                                    </label>
                                    <div class="input-group m-input-group m-input-group--square">
														<span class="input-group-addon">
															<i class="la la-street-view"></i>
														</span>

                                        <input type="text" name="street" class="form-control m-input--air" placeholder="Street">

                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <label>
                                        Locality:
                                    </label>
                                    <div class="input-group m-input-group m-input-group--square">
														<span class="input-group-addon">
															<i class="la la-location-arrow"></i>
														</span>
                                        <input name="locality" type="text" class="form-control m-input--air" placeholder="Locality">
                                    </div>
                                </div>
                            </div>
                        <div class="form-group m-form__group row">
                                <div class="col-lg-3">
                                    <label>
                                        City:
                                    </label>
                                    <div class="input-group m-input-group m-input-group--square">
														<span class="input-group-addon">
															<i class="la la-map-marker"></i>
														</span>
                                        <input type="text" name="city" class="form-control m-input--air" placeholder="City">

                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <label class="">
                                        State:
                                    </label>
                                    <div class="input-group m-input-group m-input-group--square">
														<span class="input-group-addon">
															<i class="la la-map-pin"></i>
														</span>

                                        <input type="text" name="state" class="form-control m-input--air" placeholder="State">

                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <label>
                                        Country:
                                    </label>
                                    <div class="input-group m-input-group m-input-group--square">
														<span class="input-group-addon">
															<i class="la la-map-o"></i>
														</span>
                                        <input name="country" type="text" class="form-control m-input--air" placeholder="Country">
                                    </div>
                                </div>


                            <div class="col-lg-3">
                                    <label>
                                        Pin Code:
                                    </label>
                                    <div class="input-group m-input-group m-input-group--square">
														<span class="input-group-addon">
															<i class="la la-crosshairs"></i>
														</span>
                                        <input name="pin" type="number" class="form-control m-input--air" placeholder="Pin Code">
                                    </div>
                                </div>



                            </div>



                    </div>




                    <div class="m-form m-form--fit m-form--label-align-right">
                        <div class="form-group m-form__group row">
                            <div class="row">
                                <div class="col-lg-9">
                                    <button type="submit" class="btn btn-primary btn-block">
                                        Submit
                                    </button>
                                </div>
                                <div class="col-lg-3">

                                    <button type="reset" class="btn btn-secondary">
                                        Reset
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>



                </form>
                <!--end::Form-->
            </div>
            <!--end::Portlet-->
        </div>
    </div>
    @endsection

@section('client_footer')
    <script src="{{ asset('js/seclect2.js')}}" type="text/javascript"></script>
@endsection

resources/views/client/pages/customer/showall.blade.php
@extends('client.structure')
@section('client.title', 'All Customers')
@section('client.menu.customer', 'm-menu__item--active')
@section('client')
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css">
    <div class="m-grid__item m-grid__item--fluid m-wrapper">
        <!-- BEGIN: Subheader -->
        <div class="m-subheader ">
            <div class="d-flex align-items-center">
                <div class="mr-auto">
                    <h3 class="m-subheader__title m-subheader__title--separator">
                        Dashboard
                    </h3>
                    <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                        <li class="m-nav__item m-nav__item--home">
                            <a href="#" class="m-nav__link m-nav__link--icon">
                                <i class="m-nav__link-icon la la-home"></i>
                            </a>
                        </li>
                        <li class="m-nav__separator">
                            -
                        </li>
                        <li class="m-nav__item">
                            <a href="" class="m-nav__link">
											<span class="m-nav__link-text">
												Customer
											</span>
                            </a>
                        </li>
                        <li class="m-nav__separator">
                            -
                        </li>
                        <li class="m-nav__item">
                            <a href="" class="m-nav__link">
											<span class="m-nav__link-text">
												All Customer
											</span>
                            </a>
                        </li>
                    </ul>
                </div>
                <div>
                </div>
            </div>
        </div>
        <!-- END: Subheader -->


        <div class="m-content">
            <div class="row">
                <div class="col-xl-12">
                    <!--begin::Portlet-->
                    <div class="m-portlet">
                        <div class="m-portlet__head">
                            <div class="m-portlet__head-caption">
                                <div class="m-portlet__head-title">
                                    <h3 class="m-portlet__head-text">All Customer

                                    </h3>

                                </div>
                            </div>

                            <div class="m-portlet__head-tools">
                                <ul class="m-portlet__nav">
                                    <li class="m-portlet__nav-item">
                                        <div class="m-dropdown m-dropdown--inline m-dropdown--arrow m-dropdown--align-right m-dropdown--align-push" data-dropdown-toggle="hover" aria-expanded="true">
                                            <a href="{{route('product.create')}}" class="btn btn-outline-primary m-btn m-btn--icon m-btn--outline-2x m-btn--pill m-btn--air">
															<span>
																<i class="la la-industry"></i>
																<span>
																	Add New Product
																</span>
															</span>
                                            </a>

                                        </div>
                                    </li>
                                </ul>
                            </div>



                        </div>












                        <div class="m-portlet__body">
                            <!--begin::Section-->
                            <div class="m-section">



                                <div class="m-section__content">
                                    <table class="table table-bordered" id="users-table">
                                        <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Name</th>
                                            <th>Mobile</th>
                                            <th>GstIn</th>
                                            <th>City</th>
                                        </tr>
                                        </thead>
                                    </table>



                                </div>








                            </div>




    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endsection

@section('client_footer')
    <script src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
    <script>
        $(function() {
            $('#users-table').DataTable({
                serverSide: true,
                oLanguage: {sProcessing: '<div class="" style="width: 500px; display: inline-block;z-index: 700"><img src="{{asset('/loader/ajaxloader.gif')}}" alt=""></div>'},

                ajax: '{!! route('api.get.customer') !!}',
                columns: [
                    { data: 'id', name: 'id' },
                    { data: 'name', name: 'name' },
                    { data: 'mobile', name: 'mobile' },
                    { data: 'gstin', name: 'gstin' },
                    { data: 'city', name: 'city' }
                ]
            });
        });
    </script>
@endsection

{{--

<table class="table m-table m-table--head-bg-success">
    <thead>
    <tr>
        <th>
            Product Name
        </th>
        <th>
            HSN Code
        </th>
        <th>
            IGST
        </th>
        <th>
            SGST
        </th>
        <th>
            CGST
        </th>

        <th>
            Price
        </th>

        <th>
            Created At
        </th>

        <th>
            Action
        </th>
    </tr>
    </thead>
    <tbody>

    @foreach($product as $p)

        <tr>
            <th scope="row">
                {{$p->name}}
            </th>
            <td>
                {{$p->hsn}}
            </td>
            <td>
                {{$p->igst}}%
            </td>
            <td>
                {{$p->sgst}}%
            </td>

            <td>
                {{$p->cgst}}%
            </td>

            <td>
                <i class="la la-rupee"></i> {{$p->opeaning_rate}}
            </td>

            <td>
                {{ date("d M Y", strtotime($p->created_at))}}
            </td>

            <td>
                <button type="button" class="btn m-btn--pill m-btn--air         btn-outline-primary m-btn m-btn--outline-2x ">
                    View Details
                </button>
                <a href="{{route('product.edit', ['id' => $p->id])}}">
                    <button type="button" class="btn m-btn--pill m-btn--air
                                                       btn-outline-info m-btn m-btn--outline-2x ">
                        Edit
                    </button>
                </a>
                <form action="{{route('product.destroy', ['id' => $p->id])}}" style="display: inline" method="post">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                    <button type="submit" class="btn m-btn--pill m-btn--air
                                                          btn-outline-danger m-btn m-btn--outline-2x ">
                        Delete
                    </button>
                </form>


            </td>
        </tr>
    @endforeach
    </tbody>
</table>

--}}