routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//texting purpose
Route::post('/', 'testcontroller@save')->name('test.post');
Route::get('/', 'testcontroller@index');

//end testing purpose

//manageinvoice

Route::post('/invoice', 'invoice\ManageInvoice@store')->name('inv.store.post');
Route::get('/invoice/create', 'invoice\ManageInvoice@create')->name('invoice.create.get');
Route::get('/invoice/{id}/download/pdf', 'invoice\ManageInvoice@generatePdfInvoice')->name('invoice.pdf.download');
Route::get('/invoice/{id}/details', 'invoice\ManageInvoice@InvoiceDetails')->name('invoice.details');
Route::get('/invoice', 'invoice\ManageInvoice@index')->name('invoice.dashboard.get');


//product Manage
Route::resource('product', 'product\ManageProduct');
Route::get('product/view/{id}', 'product\ManageProduct@viewdetails');
//end product Manage
//
///
///  //product client
Route::resource('customer', 'customer\CustomerController');

//end product client

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
}

app/Http/Controllers/product/ManageProduct.php
<?php

namespace App\Http\Controllers\product;

use App\Http\Controllers\Controller;
use App\Http\Requests\ProductAdd;
use App\Product;
use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;

class ManageProduct extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        return view('client.pages.product.showallproduct');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('client.pages.product.createproduct');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductAdd $request)
    {
        $s = new Product();
        $s->name = $request->name;
        $s->item_type = $request->item_type;
        $s->catogory_id = $request->catogory_id;
        $s->unit_definition = $request->unit_definition;
        $s->description = $request->description;
        $s->gst_apply = $request->gst_apply;
        $s->service_type = $request->service_type;
        $s->igst = $request->igst;
        $s->cgst = $request->cgst;
        $s->sgst = $request->sgst;
        $s->hsn = $request->hsn;
        $s->conversion_rate = $request->conversion_rate;
        $s->opeaning_quantity = $request->opeaning_quantity;
        $s->opeaning_rate = $request->opeaning_rate;
        $s->opeaning_value = $request->opeaning_value;
        $s->opeaning_taxable_rate = $request->opeaning_taxable_rate;
        $s->save();
        return back();

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $p = Product::find($id);
        return view('client.pages.product.productdetails')->with(['p' => $p]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $f = Product::find($id);
        // dd($f);
        return view('client.pages.product.editproduct', ['f' => $f]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $s = Product::find($id);
        $s->name = $request->name;
        $s->item_type = $request->item_type;
        $s->catogory_id = $request->catogory_id;
        $s->unit_definition = $request->unit_definition;
        $s->description = $request->description;
        $s->gst_apply = $request->gst_apply;
        $s->service_type = $request->service_type;
        $s->igst = $request->igst;
        $s->cgst = $request->cgst;
        $s->sgst = $request->sgst;
        $s->hsn = $request->hsn;
        $s->conversion_rate = $request->conversion_rate;
        $s->opeaning_quantity = $request->opeaning_quantity;
        $s->opeaning_rate = $request->opeaning_rate;
        $s->opeaning_value = $request->opeaning_value;
        $s->save();
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Product::destroy($id);
        //  $f->delete();
        return back();
    }

    public function productapi() {
        $i = Product::select(
            [
                'id',
                'name',
                'item_type',
                'igst',
                'hsn',
                'opeaning_taxable_rate'
            ]);

        return Datatables::of($i)
            ->addColumn('action', function ($i) {
                // return '<a href="/invoice/'.$i->id.'/details" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> View Details</a>';
                return '
                <div class="btn-group dropup"><a href="/product/' . $i->id . '/edit">
																<button type="button" class="btn btn-outline-success">
																	Edit Product
																</button>
</a>
																<button type="button" class="btn btn-outline-success dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
																	<span class="sr-only">
																		Toggle Dropdown
																	</span>
																</button>
																<div class="dropdown-menu">
																	
																	<div class="dropdown-divider"></div>
																	<a class="dropdown-item" href="#">
																		Delete Invoice
																	</a>
																</div>
															</div>';
            })
            ->editColumn('id', 'ID: {{$id}}')
            ->make(true);
    }


    public function apisearch(Request $request) {
        $query = $request->get('term','');

        $products = Product::where('name', 'LIKE', '%' . $query . '%')->take(5)->get();

        $data=array();
        foreach ($products as $product) {
            $data[]=array('value'=>$product->name,
                'id'=>$product->id,
                'service_type' => $product->item_type,
                'igst'=>$product->igst,
                'cgst'=>$product->cgst,
                'sgst'=>$product->sgst,
                'hsn'=>$product->hsn,
                'conversion_rate'=>$product->conversion_rate,
                'opeaning_rate'=>$product->opeaning_rate,
                'opeaning_taxable_rate' => $product->opeaning_taxable_rate,
                'unit_definition'=>$product->unit_definition

            );
        }
        if(count($data))
            return $data;
        else
            return ['value'=>'No Result Found','id'=>''];


    }

    public function viewdetails($id)
    {
        $p = Product::find($id);
        return view('client.pages.product.productdetails')->with(['p' => $p]);
    }
}

resources/views/client/pages/product/editproduct.blade.php
@extends('client.structure')
@section('client.title', 'Edit Product ')
@section('client.menu.product', 'm-menu__item--active')
@section('client')
    <div class="m-grid__item m-grid__item--fluid m-wrapper">
        <!-- BEGIN: Subheader -->
        <div class="m-subheader ">
            <div class="d-flex align-items-center">
                <div class="mr-auto">
                    <h3 class="m-subheader__title m-subheader__title--separator">
                        Dashboard
                    </h3>
                    <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                        <li class="m-nav__item m-nav__item--home">
                            <a href="#" class="m-nav__link m-nav__link--icon">
                                <i class="m-nav__link-icon la la-home"></i>
                            </a>
                        </li>
                        <li class="m-nav__separator">
                            -
                        </li>
                        <li class="m-nav__item">
                            <a href="#" class="m-nav__link">
											<span class="m-nav__link-text">
												Product
											</span>
                            </a>
                        </li>
                        <li class="m-nav__separator">
                            -
                        </li>
                        <li class="m-nav__item">
                            <a href="" class="m-nav__link">
											<span class="m-nav__link-text">
												Edit Product
											</span>
                            </a>
                        </li>
                    </ul>
                </div>
                <div>
                </div>
            </div>
        </div>
        <!-- END: Subheader -->
        <div class="m-content">
            <!--begin::Portlet-->
            <div class="m-portlet">
                <div class="m-portlet__head">
                    <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                            <h3 class="m-portlet__head-text">
                                Edit Product
                            </h3>
                        </div>
                    </div>


                </div>

                <!--begin::Form to add product-->
                <form class="m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed"
                      method="POST"  action="{{route('product.update', ['id' => $f->id])}}">
                    {{ csrf_field() }}

                    {{ method_field('PATCH') }}

                    <div class="m-portletbody">

                        @if ($errors->any())

                            <div class="form-group m-form__group row">
                                <div class="col-lg-12">



                                    <div class="form-group m-form__group row">

                                        <div class="col-lg-12 col-md-12 col-sm-12">

                                            <div class="m-alert m-alert--icon m-alert--icon-solid m-alert--outline alert alert-danger alert-dismissible fade show" role="alert">
                                                <div class="m-alert__icon">
                                                    <i class="flaticon-exclamation-1"></i>
                                                    <span></span>
                                                </div>
                                                <div class="m-alert__text">
                                                    <strong>
                                                        OOPS! <br>
                                                    </strong>
                                                    @foreach ($errors->all() as $error)
                                                        {{ $error }} <br>

                                                    @endforeach
                                                </div>
                                                <div class="m-alert__close">
                                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>


                                </div>
                            </div>

                        @endif

                        <div class="form-group m-form__group row">
                            <div class="col-lg-4">
                                <label>
                                    Product Name:
                                </label>
                                <input type="text" name="name"
                                       value="{{$f->name}}"
                                       class="form-control m-input--air" placeholder="Required">
                                <span class="m-form__help">
														Name full name of the Product
													</span>
                            </div>
                            <div class="col-lg-4">
                                <label class="">
                                    Short Description:
                                </label>
                                <input type="text" value="{{$f->description}}" name="description" class="form-control m-input--air" placeholder="Optional">
                                <span class="m-form__help">
														Short Description About Product
													</span>
                            </div>
                            <div class="col-lg-4">
                                <label>
                                    Price:
                                </label>
                                <div class="input-group m-input-group m-input-group--square">
														<span class="input-group-addon">
															<i class="la la-inr"></i>
														</span>
                                    <input name="opeaning_rate" value="{{$f->opeaning_rate}}" type="number" class="form-control m-input--air" placeholder="">
                                </div>
                                <span class="m-form__help">
														Opening Price of the Product
													</span>
                            </div>
                        </div>
                        <div class="form-group m-form__group row">
                            <div class="col-lg-4">
                                <label class="">
                                    SGST:
                                </label>
                                <select name="sgst" class="form-control m-input--air">

                                    <option value="{{$f->sgst}}">{{$f->sgst}}%</option>
                                    <option value="0">0%</option>
                                    <option value="2.5">2.5%</option>
                                    <option value="4.5">4.5%</option>
                                    <option value="6">6%</option>
                                    <option value="9">9%</option>
                                    <option value="14">14%</option>
                                </select>
                                <span class="m-form__help">
														Enter SGST of the product
													</span>
                            </div>
                            <div class="col-lg-4">
                                <label class="">
                                    CGST:
                                </label>
                                <select name="cgst" class="form-control m-input--air">
                                    <option value="{{$f->cgst}}">{{$f->cgst}}%</option>
                                    <option value="0">0%</option>
                                    <option value="2.5">2.5%</option>
                                    <option value="4.5">4.5%</option>
                                    <option value="6">6%</option>
                                    <option value="9">9%</option>
                                    <option value="14">14%</option>
                                </select>
                                <span class="m-form__help">
														Enter CGST of the product
													</span>
                            </div>
                            <div class="col-lg-4">
                                <label class="">
                                    IGST:
                                </label>
                                <select name="igst" class="form-control m-input--air">
                                    <option value="{{$f->igst}}">{{$f->igst}}%</option>
                                    <option value="2.5">2.5%</option>
                                    <option value="4.5">4.5%</option>
                                    <option value="6">6%</option>
                                    <option value="9">9%</option>
                                    <option value="14">14%</option>
                                </select>
                                <span class="m-form__help">
                                    IGST is auto calculated
													</span>
                            </div>
                        </div>
                        <div class="form-group m-form__group row">
                            <div class="col-lg-4">
                                <label >
                                    Unit Definition:
                                </label>
                                <div class="m-input-icon m-input-icon--right">
                                    <select class="form-control m-input--air"
                                            name="unit_definition">
                                        <option value="{{$f->unit_definition}}">{{$f->unit_definition}}</option>
                                        <option value="cm">CM</option>
                                        <option value="MM">MM</option>
                                        <option value="KG">KG</option>
                                        <option value="PIECE">PIECE</option>
                                        <option value="GM">GM</option>
                                        <option value="UNIT">UNITS</option>
                                        <option value="OTHER">OTHER</option>

                                    </select>

                                </div>
                                <span class="m-form__help">
														Unit Definition
													</span>
                            </div>
                            <div class="col-lg-4">
                                <label>
                                    HSN CODE:
                                </label>
                                <div class="input-group m-input-group m-input-group--square">

                                    <input name="hsn" type="text" value="{{$f->hsn}}" class="form-control m-input--air" placeholder="Required">
                                </div>
                                <span class="m-form__help">
														Enter HSN of the Product
													</span>
                            </div>


                            <div class="col-lg-4">
                                <label>
                                    Conversion Rate:
                                </label>
                                <div class="input-group m-input-group m-input-group--square">

                                    <input type="text" name="conversion_rate" value="{{$f->conversion_rate}}" class="form-control m-input--air" placeholder="Required">
                                </div>
                                <span class="m-form__help">
														Conversion Rate of the Product
													</span>
                            </div>




                        </div>
                    </div>




                    <div class="m-form m-form--fit m-form--label-align-right">
                        <div class="form-group m-form__group row">
                            <div class="row">
                                <div class="col-lg-6">
                                    <button type="submit" class="btn btn-primary">
                                        Submit
                                    </button>
                                </div>
                                <div class="col-lg-6">

                                    <a href="/product" class="btn btn-secondary">
Back
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>



                </form>
                <!--end::Form-->
            </div>
            <!--end::Portlet-->
        </div>
    </div>
@endsection

@section('client_footer')
    <script src="{{ asset('js/seclect2.js')}}" type="text/javascript"></script>
@endsection

resources/views/client/pages/product/showallproduct.blade.php
@extends('client.structure')
@section('client.title', 'All Products')
@section('client.menu.product', 'm-menu__item--active')
@section('client')
    <link rel="stylesheet" href="{{asset('css/client/datatable.min.css')}}">


    <div class="m-grid__item m-grid__item--fluid m-wrapper">
        <!-- BEGIN: Subheader -->
        <div class="m-subheader ">
            <div class="d-flex align-items-center">
                <div class="mr-auto">
                    <h3 class="m-subheader__title m-subheader__title--separator">
                        Dashboard
                    </h3>
                    <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                        <li class="m-nav__item m-nav__item--home">
                            <a href="#" class="m-nav__link m-nav__link--icon">
                                <i class="m-nav__link-icon la la-home"></i>
                            </a>
                        </li>
                        <li class="m-nav__separator">
                            -
                        </li>
                        <li class="m-nav__item">
                            <a href="" class="m-nav__link">
											<span class="m-nav__link-text">
												Product
											</span>
                            </a>
                        </li>
                        <li class="m-nav__separator">
                            -
                        </li>
                        <li class="m-nav__item">
                            <a href="" class="m-nav__link">
											<span class="m-nav__link-text">
												All Product
											</span>
                            </a>
                        </li>
                    </ul>
                </div>
                <div>
                </div>
            </div>
        </div>
        <!-- END: Subheader -->


        <div class="m-content">
            <div class="row">
                <div class="col-xl-12">
                    <!--begin::Portlet-->
                    <div class="m-portlet">
                        <div class="m-portlet__head">
                            <div class="m-portlet__head-caption">
                                <div class="m-portlet__head-title">
                                    <h3 class="m-portlet__head-text">View All Products

                                    </h3>

                                </div>
                            </div>

                            <div class="m-portlet__head-tools">
                                <ul class="m-portlet__nav">
                                    <li class="m-portlet__nav-item">
                                        <div class="m-dropdown m-dropdown--inline m-dropdown--arrow m-dropdown--align-right m-dropdown--align-push"
                                             data-dropdown-toggle="hover" aria-expanded="true">
                                            <a href="{{route('product.create')}}"
                                               class="btn btn-outline-primary m-btn m-btn--icon m-btn--outline-2x m-btn--pill m-btn--air">
															<span>
																<i class="la la-industry"></i>
																<span>
																	Add New Product
																</span>
															</span>
                                            </a>

                                        </div>
                                    </li>
                                </ul>
                            </div>


                        </div>


                        <div class="m-portlet__body">
                            <!--begin::Section-->
                            <div class="m-section">


                                <div class="m-section__content">
                                    <table class="table table-bordered product-table" id="product-table">
                                        <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Type</th>
                                            <th>GSTIN</th>
                                            <th>AMOUNT</th>
                                            <th>CREATED At</th>
                                            <th>Details</th>
                                        </tr>
                                        </thead>
                                    </table>


                                </div>


                            </div>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @endsection

@section('client_footer')
    <script src="{{asset('js/client/datatable.min.js')}}"></script>
    <script>
        $(function () {
            $('#product-table').DataTable({
                processing: true,
                serverSide: true,
                oLanguage: {sProcessing: '<div class="" style="width: 500px; height:100%; display: inline-block;z-index: 700"><img src="{{asset('/loader/ajaxloader.gif')}}" alt=""></div>'},

                ajax: '{{route('api.get.product')}}',
                columns: [
                    {data: 'name', name: 'name'},
                    {data: 'item_type', name: 'item_type'},
                    {data: 'igst', name: 'igst'},
                    {data: 'hsn', name: 'hsn'},

                    {data: 'opeaning_taxable_rate', name: 'action', orderable: false, searchable: false},
                    {data: 'action', name: 'action', orderable: false, searchable: false}


                ]
            });

        });
    </script>

@endsection